### ISSUE TITLE
Remote tool or extend http://api.call-cc.org/ for all the scheme implementation in SRFIs

### ISSUE THREAD

**Issue by APIPLM** [schemedoc/api-server#2]
Went through the readme is such a pleasure. Most like [slime/slime](https://github.com/slime/slime/) is a remote debug tool integrating into Emacs for common lisp, and it is part of IDE tool set. and then by this inspired, Geiser was created for the same purpose (remote debug) for scheme language (different dialect schemes). And `http://api.call-cc.org` have powerful way to navigate the scheme document in the chicken community by search node name of the document. What would this project like to be? 

OpenAPI sound like quite popular as well. that way they [build the documents](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#operationObject) 

What ever the way would be?  The first thing would be done is that the index in these meta-data for these document ( R5RS, R6RS R7RS and SRFIs)

**Comment by lassik** [comment]
> The first thing would be done is that the index in these meta-data for these document ( R5RS, R6RS R7RS and SRFIs)

Exactly. I think everything under github.com/schemedoc should go into the API. It will take a long time to accomplish, but we're not in a hurry :)

**Comment by lassik** [comment]
The other questions are answered in #1.
